FROM alpine:latest 

 # Install required packages for the Iso/Image
RUN apk add --no-cache \   
	fastfetch \
	nano

ENV NAME="Gabriel" \
    COURSE="Docker"

CMD sh -c "\
	echo ' ✅ Lauch successful' && \
	'fastfetch' "
